export class StockDetailed {
    constructor(
      public symbol: string,
      public price: number, 
      public changesPercentage: number, 
      public change: number, 
      public dayLow: number, 
      public dayHigh: number, 
      public yearHigh: number,
      public yearLow: number, 
      public marketCap: number, 
      public priceAvg50: number, 
      public priceAvg200: number,  
      public volume: number,
      public avgVolume: number, 
      public date: string,
      public open: number,
      public previousClose: number, 
      public eps: number, 
      public pe: number,
      public exchange: string,  
      public earningsAnnouncement: string,  
      public timestamp: Date, 
      public sharesOutstanding: number,
      public companyName: string,
      public sector: string,
      public industry: string, 
      public currency: string,
      public stockExchange: string,
      public exchangeShortName: string,
      public country: string,
      public isEtf: string, 
      public isActivelyTrading: string,   
      public name: string,
      public bigDip: boolean,
      public bigDipPercentage: number,
      public supportLevelPrice: number,
      public supportLevelStrength: string,
      public fiveMinuteDip: boolean, 
      public fiveMinuteDipPercentage: number,
      public hotListStocks: []
    ) {}
  }